In [1]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [2]:
v = np.arange(1, 11, 1, dtype=int)
v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [3]:
a = np.zeros((3, 3), dtype=int)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [4]:
a = np.random.randint(1, 11, size=(5, 5))
a

array([[ 5,  4,  7,  6,  3],
       [ 9,  4,  3,  1,  8],
       [ 7,  6,  4,  6,  5],
       [ 6,  1,  8,  4,  1],
       [10,  5,  2,  9,  5]])

4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [5]:
a = np.random.random(size=(4, 4))
a

array([[0.92514683, 0.56072065, 0.1353546 , 0.00375975],
       [0.28790045, 0.19071659, 0.38222197, 0.8691245 ],
       [0.33219833, 0.25039437, 0.93227787, 0.10974203],
       [0.28605641, 0.96838851, 0.74892859, 0.29510213]])

5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [6]:
a = np.random.randint(1, 10, size=5)
a

array([8, 7, 5, 3, 9])

In [7]:
b = np.random.randint(1, 10, size=5)
b

array([1, 8, 6, 1, 3])

In [8]:
a + b

array([ 9, 15, 11,  4, 12])

In [9]:
a - b

array([ 7, -1, -1,  2,  6])

In [10]:
a * b

array([ 8, 56, 30,  3, 27])

6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [11]:
a = np.random.randint(1, 10, size=7)
b = np.random.randint(1, 10, size=7)
np.dot(a, b)

151

7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [12]:
a = np.random.randint(1, 10, size=(2, 2))
b = np.random.randint(1, 10, size=(2, 3))
np.dot(a, b)

array([[44, 36, 52],
       [61, 53, 72]])

8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [13]:
a = np.random.randint(1, 10, size=(3, 3))
a

array([[4, 9, 6],
       [5, 7, 2],
       [7, 3, 6]])

In [14]:
np.linalg.inv(a)

array([[-0.17647059,  0.17647059,  0.11764706],
       [ 0.07843137,  0.08823529, -0.10784314],
       [ 0.16666667, -0.25      ,  0.08333333]])

9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [15]:
a = np.random.random(size=(4, 4))
a

array([[0.41368895, 0.97666727, 0.13108367, 0.55310553],
       [0.00535253, 0.55543925, 0.61235602, 0.68163128],
       [0.32280318, 0.25078071, 0.96748774, 0.56705061],
       [0.16259824, 0.57656754, 0.26927223, 0.12536718]])

In [16]:
a.T

array([[0.41368895, 0.00535253, 0.32280318, 0.16259824],
       [0.97666727, 0.55543925, 0.25078071, 0.57656754],
       [0.13108367, 0.61235602, 0.96748774, 0.26927223],
       [0.55310553, 0.68163128, 0.56705061, 0.12536718]])

10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [17]:
a = np.random.randint(1, 10, size=(3, 4))
a

array([[5, 9, 9, 4],
       [4, 9, 8, 4],
       [9, 5, 6, 8]])

In [18]:
v = np.random.randint(1, 11, size=4)
v

array([2, 5, 1, 7])

In [19]:
a * v

array([[10, 45,  9, 28],
       [ 8, 45,  8, 28],
       [18, 25,  6, 56]])

11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [20]:
a = np.random.random(size=(2, 3))
a

array([[0.6205475 , 0.47706167, 0.97614859],
       [0.30353351, 0.96609968, 0.69863871]])

In [21]:
v = np.random.random(size=3)
v

array([0.13223163, 0.60133887, 0.34609584])

In [22]:
a * v

array([[0.08205601, 0.28687573, 0.33784096],
       [0.04013673, 0.58095329, 0.24179595]])

12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [23]:
a_1 = np.random.randint(1, 10, size=(2, 2))
a_1

array([[6, 2],
       [3, 6]])

In [24]:
a_2 = np.random.randint(1, 10, size=(2, 2))
a_2

array([[9, 8],
       [9, 6]])

In [25]:
a_1 * a_2

array([[54, 16],
       [27, 36]])

13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [26]:
np.dot(a_1, a_2)

array([[72, 60],
       [81, 60]])

14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [27]:
a = np.random.randint(1, 100, size=(5, 5))
a

array([[60, 96, 12, 87, 17],
       [74, 30, 85,  7, 78],
       [ 1, 40, 61, 13, 62],
       [42, 86, 25, 71, 85],
       [94, 59, 12, 70, 44]])

In [28]:
a.sum()

1311

15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [29]:
a_1 = np.random.randint(1, 10, size=(4, 4))
a_1

array([[1, 5, 6, 1],
       [6, 3, 8, 8],
       [2, 3, 5, 9],
       [6, 4, 4, 6]])

In [30]:
a_2 = np.random.randint(1, 10, size=(4, 4))
a_2

array([[1, 9, 7, 3],
       [6, 3, 9, 7],
       [7, 8, 7, 7],
       [7, 7, 3, 7]])

In [31]:
a_1 - a_2

array([[ 0, -4, -1, -2],
       [ 0,  0, -1,  1],
       [-5, -5, -2,  2],
       [-1, -3,  1, -1]])

16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [32]:
a = np.random.random(size=(3, 3))
a

array([[0.8674361 , 0.16149602, 0.89358214],
       [0.49211178, 0.67417257, 0.2441214 ],
       [0.59624612, 0.93154429, 0.26729682]])

In [33]:
sum(a.T)

array([1.92251426, 1.41040575, 1.79508723])

In [34]:
a.sum(axis=1)

array([1.92251426, 1.41040575, 1.79508723])

17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [35]:
a = np.random.randint(1, 20, size=(3, 4))
a

array([[ 3,  6, 12, 11],
       [ 8,  6, 18,  9],
       [ 6, 16,  7, 18]])

In [36]:
a * a

array([[  9,  36, 144, 121],
       [ 64,  36, 324,  81],
       [ 36, 256,  49, 324]])

In [37]:
a ** 2

array([[  9,  36, 144, 121],
       [ 64,  36, 324,  81],
       [ 36, 256,  49, 324]])

18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [38]:
v = np.random.randint(1, 50, size=4)
v

array([49, 47,  2, 21])

In [39]:
v ** 0.5

array([7.        , 6.8556546 , 1.41421356, 4.58257569])

In [40]:
np.sqrt(v)

array([7.        , 6.8556546 , 1.41421356, 4.58257569])

**Завдання 2 (додаткове, за бажанням)**

1. Замініть усі непарні числа в arr на -1 arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
for index, value in enumerate(arr):
    if value % 2:
        arr[value] = -1

arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [42]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

2. Створіть та перетворіть 1D-масив на 2D-масив із 2 рядками

In [43]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = arr.reshape((5, 2))

arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

3. Створіть два двовимірні масиви а і b, та складіть масиви їх вертикально

> Додати блок цитати



In [44]:
a = np.random.randint(-10, 10, size=(2, 2))
a

array([[ 2,  8],
       [ 0, -6]])

In [45]:
b = np.random.randint(-10, 10, size=(2, 2))
b

array([[ -4,   4],
       [-10, -10]])

In [46]:
res = a + b
res

array([[ -2,  12],
       [-10, -16]])

In [47]:
res = np.vstack((a, b))
res

array([[  2,   8],
       [  0,  -6],
       [ -4,   4],
       [-10, -10]])

4. Створіть наступний шаблон без жорсткого кодування(Hard coding) . Використовуйте лише функції Numpy і наведений нижче масив введення Input:a = np.array([1,2,3])

Output:array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [48]:
a = np.array([1,2,3])
# Повторення кожного елемента 3 рази
part1 = np.repeat(a, 3)
# Повторення всього масиву 3 рази
part2 = np.tile(a, 3)
output = np.concatenate((part1, part2))
output

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

5. Отримайте спільні елементи між a і b

a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

In [49]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

6. Отримайте позиції перших 5 максимальних значень у заданому масиві a

np.random.seed(100) a = np.random.uniform(1,50, 20)

In [50]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
a

array([27.62684215, 14.64009987, 21.80136195, 42.39403048,  1.23122395,
        6.95688692, 33.86670515, 41.466785  ,  7.69862289, 29.17957314,
       44.67477576, 11.25090398, 10.08108276,  6.31046763, 11.76517714,
       48.95256545, 40.77247431,  9.42510962, 40.99501269, 14.42961361])

In [51]:
# Отримуємо індекси відсортованих значень у порядку зростання
sorted_indices = np.argsort(a)
# Беремо останні 5 індексів (найбільші значення) у зворотному порядку
top_5_indices = sorted_indices[-5:][::-1]
top_5_indices

array([15, 10,  3,  7, 18])

In [52]:
top_5 = a[top_5_indices]
top_5

array([48.95256545, 44.67477576, 42.39403048, 41.466785  , 40.99501269])

7. Вилучіть усі значення NaN із одновимірного масиву

а=np.array([1,2,3,np.nan,5,6,7,np.nan])

In [53]:
a = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])
a_clean = a[~np.isnan(a)]
a_clean

array([1., 2., 3., 5., 6., 7.])

In [54]:
a = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])
a_clean = np.array([el for el in a if not np.isnan(el)])
a_clean

array([1., 2., 3., 5., 6., 7.])

8. Обчисліть евклідову відстань між двома масивами a і b.

a = np.array([1,2,3,4,5]) b = np.array([4,5,6,7,8])

In [55]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])
distance = np.linalg.norm(a - b)
distance

6.708203932499369

9. Знайдіть індекс 5-го повторення числа 1 у масиві x

x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

In [56]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
rep_count = 0
found_idx = None
for i, val in enumerate(x):
  if val == 1:
    rep_count += 1
    if rep_count == 5:
      found_idx = i

found_idx

8

In [57]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
indices = np.where(x == 1)[0]
fifth_occurrence_index = indices[4]
fifth_occurrence_index

8

10. Знайдіть повторювані записи (від 2-го випадку повторення і далі) у заданому масиві і позначте їх як True. Перше повторення має бути False.

Input np.random.seed(100) a = np.random.randint(0, 5, 10)

[0 0 3 0 2 4 2 2 2 2] #Output [False True False True False False True True True True]

In [58]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
a

array([0, 0, 3, 0, 2, 4, 2, 2, 2, 2])

In [59]:
marks = np.zeros_like(a, dtype=bool)
seen = {}
for i, value in enumerate(a):
    if value in seen:
        marks[i] = True
    else:
        seen[value] = 1
marks

array([False,  True, False,  True, False, False,  True,  True,  True,
        True])